name:                WeigthControl
version:             0.1.0.0
github:              "nicvaltel/WeigthControl"
license:             BSD3
author:              "nicvaltel"
maintainer:          "nicvaltel@gmail.com"
copyright:           "2023 nicvaltel"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/nicvaltel/WeigthControl#readme>

dependencies:
- base >= 4.7 && < 5
- telegram-bot-simple
- telegram-bot-api
- text
- time
- bytestring
- mtl
- transformers
- postgresql-simple
- postgresql-simple-migration
- dotenv
- data-has
- record-hasfield
- either
- exceptions
- resource-pool
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  WeigthControl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WeigthControl

